name: Build docker image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Compute next candidate version
      id: next
      uses: InterficieIS/docker-version-bydate@v2.0.0
      with:
        image: interficie/ssh-tunnel

    - name: Build the tagged Docker image
      run: docker build . --tag ${{ steps.next.outputs.version }} --tag interficie/ssh-tunnel:latest

    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      if: ${{ github.event_name == 'push' && github.event.ref == 'refs/heads/master' }}

    - name: Push the tagged Docker image
      run: docker push interficie/ssh-tunnel
      if: ${{ github.event_name == 'push' && github.event.ref == 'refs/heads/master' }}
